DATA:
  VIDEO_DIR_PATH: /media/dml/e5afa40a-df1a-4c60-8623-87e2a51c3a09/ego4d/new/v1/full_scale
  ANN_PATH: /media/dml/e5afa40a-df1a-4c60-8623-87e2a51c3a09/ego4d/new/v1/annotations/fho_oscc-pnr_train.json
  SPLIT_PATH: /media/dml/e5afa40a-df1a-4c60-8623-87e2a51c3a09/ego4d/new/v1
  CLIPS_SAVE_PATH: /media/dml/e5afa40a-df1a-4c60-8623-87e2a51c3a09/ego4d/new/v1/positive_clips
  NO_SC_PATH: /media/dml/e5afa40a-df1a-4c60-8623-87e2a51c3a09/ego4d/new/v1/negative_clips
  NO_SC_SPLIT_PATH: /media/dml/e5afa40a-df1a-4c60-8623-87e2a51c3a09/ego4d/new/v1/annotations/fho_oscc-pnr_test_unannotated.json
  SAMPLING_FPS: 2
  CLIP_LEN_SEC: 8
  CROP_SIZE: 225
  TASK: "state_change_detection_and_keyframe_localization"
TRAIN:
  TRAIN_ENABLE: True
  DATASET: StateChangeDetectionAndKeyframeLocalisation
  BATCH_SIZE: 4
TEST:
  ENABLE: False
  BATCH_SIZE: 2
  JSON: /media/dml/e5afa40a-df1a-4c60-8623-87e2a51c3a09/ego4d/new/v1/annotations/fho_oscc-pnr_test_unannotated.json
  VAL_JSON: /media/dml/e5afa40a-df1a-4c60-8623-87e2a51c3a09/ego4d/new/v1/annotations/fho_oscc-pnr_val.json
  DATASET: StateChangeDetectionAndKeyframeLocalisation


DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
  SHUFFLE: True
  IS_NO_STATE_CHANGE: True
MISC:
  FAST_DEV_RUN: False
  NUM_GPUS: 1
  OUTPUT_DIR: /home/dml/PycharmProjects/Ego4D/Ego4dBenchmark/hands-and-objects/2022-1-1_main_exp_lr-0.001_temporal-filters-3_num-states-2

MODEL:
  ARCH: "slow_layer5"
  NUM_CLASSES: [1]
  NUM_STATE_CLASSES: [2]
  HEAD_ACT: softmax
  MODEL_NAME: DualHeadResNet
SOLVER:
  BASE_LR: 0.0001
  MAX_EPOCH: 100
